version: "2"
run:
  go: "1.26"
linters:
  enable:
    - exhaustive
    - gocritic
    - misspell
    - nilerr
    - prealloc
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gocritic
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/chefenfd
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
